exports.Messages = {
    BOOK_DOES_NOT_EXIST : 'BOOK DOES NOT EXIST',
    ERROR_ADDING_BOOK : 'ERROR ADDING BOOK',
    ERROR_DELETING_BOOK : 'ERROR DELETING BOOK',
    ERROR_GETTING_BOOK : 'ERROR GETTING BOOK',
    ERROR_UPDATING_BOOK : 'ERROR UPDATING BOOK',
}